export const products = [
  {
    id: 1,
    name: "Premium Wireless Headphones",
    description:
      "Noise-cancelling headphones with premium sound quality and 30-hour battery life.",
    price: 199.99,
    category: "electronics",
    rating: 4.7,
    inventory: 42,
    images: [
      "headphones-main.jpg",
      "headphones-side.jpg",
      "headphones-case.jpg",
    ],
    features: [
      "Active noise cancellation",
      "30-hour battery life",
      "Comfortable ear cushions",
      "Voice assistant compatible",
      "Quick charge (5 min for 3 hours)",
    ],
    colors: ["black", "silver", "blue"],
  },
  {
    id: 2,
    name: "Smart Fitness Watch",
    description:
      "Track your health metrics, workouts, and receive notifications on this sleek fitness watch.",
    price: 149.99,
    category: "electronics",
    rating: 4.5,
    inventory: 78,
    images: ["watch-front.jpg", "watch-side.jpg", "watch-app.jpg"],
    features: [
      "Heart rate monitoring",
      "Sleep tracking",
      "Water resistant to 50m",
      "7-day battery life",
      "GPS tracking",
    ],
    colors: ["black", "white", "green"],
  },
  {
    id: 3,
    name: "Ultra-thin Laptop",
    description: "Powerful, lightweight laptop for professionals on the go.",
    price: 1299.99,
    category: "electronics",
    rating: 4.8,
    inventory: 15,
    images: ["laptop-open.jpg", "laptop-closed.jpg", "laptop-side.jpg"],
    features: [
      "16GB RAM",
      "512GB SSD",
      "14-inch 4K display",
      "12-hour battery life",
      "Backlit keyboard",
    ],
    colors: ["silver", "space gray"],
  },
  {
    id: 4,
    name: "Designer T-shirt",
    description: "Premium cotton t-shirt with unique designer print.",
    price: 39.99,
    category: "clothing",
    rating: 4.3,
    inventory: 210,
    images: ["tshirt-front.jpg", "tshirt-back.jpg", "tshirt-detail.jpg"],
    features: [
      "100% organic cotton",
      "Eco-friendly dyes",
      "Reinforced stitching",
      "Pre-shrunk fabric",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["white", "black", "navy", "red"],
  },
  {
    id: 5,
    name: "Gourmet Coffee Maker",
    description:
      "Precision brewing coffee machine for barista-quality coffee at home.",
    price: 129.99,
    category: "home",
    rating: 4.6,
    inventory: 38,
    images: [
      "coffeemaker-front.jpg",
      "coffeemaker-side.jpg",
      "coffeemaker-top.jpg",
    ],
    features: [
      "Precision temperature control",
      "Multiple brewing styles",
      "Built-in grinder",
      "Timer function",
      "Self-cleaning",
    ],
    colors: ["black", "stainless steel"],
  },
  {
    id: 6,
    name: "Ergonomic Office Chair",
    description: "Comfortable ergonomic chair designed for long working hours.",
    price: 249.99,
    category: "furniture",
    rating: 4.8,
    inventory: 23,
    images: ["chair-front.jpg", "chair-side.jpg", "chair-back.jpg"],
    features: [
      "Adjustable lumbar support",
      "Breathable mesh back",
      "Adjustable armrests",
      "360-degree swivel",
      "Heavy-duty base",
    ],
    colors: ["black", "gray", "blue"],
  },
];

export const categories = [
  { id: "electronics", name: "Electronics" },
  { id: "clothing", name: "Clothing" },
  { id: "home", name: "Home & Kitchen" },
  { id: "furniture", name: "Furniture" },
];
